### ISSUE TITLE
 All the RGB images are flipped in Y axis

### ISSUE THREAD

**Issue by wizardjo** [Unity-Technologies/com.unity.perception#310] opened 2021-05-05 22:01 UTC
Hi,

There is a some strange behaviour in the Unity Simulation Capture 0.0.10-preview.22 library. All the RGB images appears flipped in the Y axis. This error doesnt happend in Unity Simulation Capture 0.0.10-preview.21.

Thank you

**Comment by mkamalza** [comment] 2021-05-05 22:33
Hi, 

We have heard about this issue once before but have not been able to reproduce it yet. Can you please provide more information about your setup (Unity version, Perception package version, OS). 

Also, if possible, it would help if you could share your Unity project with us.

**Comment by wizardjo** [comment] 2021-05-06 14:14
Hi @mkamalza 

Unity version -> 2019.4.25f1
Perception package -> 0.8.0 preview.3
Simulation Capture -> 0.0.10 preview.22

**Comment by mkamalza** [comment] 2021-05-06 20:00
Thank you. And is this on Windows?

**Comment by wizardjo** [comment] 2021-05-06 20:10
Yes. Windows 10, using URP. 

Note: When I created a build for Linux (to run in Unity Sim) the problems does not appear.

**Comment by mkamalza** [comment] 2021-05-06 22:57
Thank you. I am now able to consistently reproduce this. It happens when in the camera settings, post processing is enabled and FXAA anti-aliasing is disabled. So as a temporary work-around, please enable FXAA. Meanwhile, we will be looking into this to fix it as soon as possible.

**Comment by JonathanHUnity** [comment] 2021-11-08 16:54
The new 0.9.0 version of the package has a fix for this issue. Let us know if it does not work.

**Comment by karthikm-0** [comment] 2022-03-13 18:57
Sorry to bump this but I had the same issue with 0.10.0-preview.1 of the Perception package without using the Simulation package. This occurred regardless of whether post processing. Downgrading to 0.9.0-preview.2 fixed it for me. This was using Unity 2020.3.21f1 on Ubuntu.

**Comment by JonathanHUnity** [comment] 2022-03-14 16:02
Thanks for the report. We are investigating.

**Comment by jmacpereira** [comment] 2022-03-25 16:07
I'm having the same Y-flipping issue on the newest preview release, plus an additional issue which didn't happen on 0.9.0 and seems to be caused by the same change: the RGB image comes out darker than it should. This happens only when using OpenGL, switching to Vulkan fixes the darkness but not the Y-flipping:

**Normal image rendered by a Camera, looks the same on OpenGL and Vulkan:**
<img src="https://user-images.githubusercontent.com/84857036/160157210-0e6c4151-a933-46dc-952a-f77f9ef411a3.png" width="500"/>

**Image rendered by PerceptionCamera with OpenGL:**
<img src="https://user-images.githubusercontent.com/84857036/160157886-0fc7c062-34e8-4cf6-b5ee-376b6e0bcfe5.png" width="500"/>

**Image rendered by PerceptionCamera with Vulkan:**
<img src="https://user-images.githubusercontent.com/84857036/160157987-c624d274-4c24-475f-a544-812e81de7bb1.png" width="500"/>


Using Unity 2020.3.31f1 on Ubuntu.

**Comment by an99990** [comment] 2022-03-29 17:57
same issue but enabling FXXA doesnt fix it for me.

**Comment by JonathanHUnity** [comment] 2022-03-30 18:30
We are working on a fix. @jmacpereira  this issue should go away if you switch your project to use Vulkan instead of OpenGL. Can you confirm that this works for you?

**Comment by JonathanHUnity** [comment] 2022-03-30 18:31
Sorry, I just noticed that you have reproduced this on Vulkan as well. I have thus far not been able to reproduce this issue on Vulkan. If you have a project that you can provide, send us an email at computer-vision@unity3d.com and I will send you instructions on how to send it to us securely. Thank you!

**Comment by jmacpereira** [comment] 2022-03-31 12:57
Hi Jonathan, thanks for the support. We've realized the y-flipping doesn't happen if the `Camera` targeted by `PerceptionCamera` doesn't have a `targetTexture`.

However, we need to set the camera resolution when it's created in code, so we're doing
`gameObject.GetComponent<Camera>().targetTexture = new RenderTexture(width, height, 0);`
and doing this causes the image to flip.

Also tried setting different `RenderTextureFormat`s on the constructor, but none of them fixed the flipping, and some caused the same darkness problem as OpenGL.

I've sent an email explaining the bug and attached an example project to the address you mentioned. This project has no sensitive code / assets.

Thanks again

**Comment by jmacpereira** [comment] 2022-04-20 15:41
Just updated to 0.11.1 and this is now fixed, both for OpenGL and Vulkan.

Thank you for the quick fix 🎉 I think this can be closed for now.

**Comment by JonathanHUnity** [comment] 2022-04-20 17:25
Great! Thank you for confirming @jmacpereira

**Closed by JonathanHUnity** 2022-04-20 17:25 UTC
Labels: bug
