### ISSUE TITLE
Physics engine is not updating within the scenario iteration

### ISSUE THREAD

**Issue by cgtimme** [Unity-Technologies/com.unity.perception#246] opened 2021-03-11 13:37 UTC
**Purpose of scenario:**
We want to rotate randomly an object and place a Decale Projector on the rotated object. 
Therefor we want to receive the objects face normal.

We run a script which we call from our ExplorerEvent (public class ExplorerEvent : Randomizer) to execute after the RotationRandomizer.
This script is using Physics.Raycast to hit the object and get the RaycastHit.point and
RaycastHit.normal to place a Decal Projector. 
The Raycast is called in average about 1000 times (per frame) to get different hits on the object because the final place also depends on other factors.

**Issue:**
By analyzing the scene, we concluded that there is an offset between the frames: The Decal is rotated right to the former (frame 0) rotation of the object but not to the current rotation (frame 1).

We did not get a different result either by reducing the amount of Raycasts (like not 1000 but 1) or using more frames per iteration. 
Changes of parameters (like fixed timesteps) in the Time Project Settings have also had no effects.

Please see the attached images. 
Here you can see that the Decal Projector in the second frame adopts the normal of the object in the first frame. This pattern runs through all the other frames.

**Our guesses:**
- Physics engine is not updating within the scenario iteration.
- In the scenarios can be called usual randomizers only not custom Events disguised as randomizers.

We would be grateful if you could help us. 
If further information is needed to discuss the problem, we will share it with you.

[
<img width="645" alt="DecalAufObject_frame05" src="https://user-images.githubusercontent.com/80466429/110795334-ff8b4080-8276-11eb-99fa-2d403e31efbd.PNG">
<img width="645" alt="DecalAufObject_frame04" src="https://user-images.githubusercontent.com/80466429/110795342-01ed9a80-8277-11eb-95f3-47118a323b35.PNG">
<img width="647" alt="DecalAufObject_frame03" src="https://user-images.githubusercontent.com/80466429/110795348-02863100-8277-11eb-9f24-c6939dc17064.PNG">
<img width="650" alt="DecalAufObject_frame02" src="https://user-images.githubusercontent.com/80466429/110795351-03b75e00-8277-11eb-9929-05f6216bc478.PNG">
<img width="642" alt="DecalAufObject_frame01" src="https://user-images.githubusercontent.com/80466429/110795355-04e88b00-8277-11eb-8f4d-6c9271c7f585.PNG">
<img width="482" alt="Scenario" src="https://user-images.githubusercontent.com/80466429/110795360-05812180-8277-11eb-96e1-4e1783fcbfd8.PNG">

](url)

**Comment by mkamalza** [comment] 2021-03-11 17:41
Hi,

To be able to narrow down on the root cause here, it would help to know a bit more about your setup:
* How is your Perception Camera timing setup? Can you please post a screenshot of it?
* The issue might be a delay between when the event is issued and when the raycasts are done. Can you share the code for ExplorerEvent? That might help here.

**Comment by cgtimme** [comment] 2021-03-11 18:40
Thanks for the quick response. 

After checking the sequences in detail, we found the following:
1. iterationEnd is called at the beginning of the next frame before iterationStart.
2. the rotation of the RotationRandomizer is only changed before the rendering process in the physics. (called "end of frame" in the attached image).

This means that no matter when the Explorer function is triggered, we will never get both the decal and the rotation of the object correct before the render process. 

This also means that in the next frame in the middle of the process everything is correct (red line marked with the correct sign in the attached image).

By a sequence offset (per frame alternately either the RotationRandomizer or the Explorer is active) we get the correct result in every second frame. 

Please find attached a sketch that roughly describes the process and the screenshot of the camera timing setup.

![Process](https://user-images.githubusercontent.com/80466429/110837125-25c5d600-82a1-11eb-828c-7e4166c92bf1.png)

![CameraTimingSetUp](https://user-images.githubusercontent.com/80466429/110837294-54dc4780-82a1-11eb-90cb-9e31b974b5ad.PNG)

**Comment by mkamalza** [comment] 2021-03-11 19:44
Thank you for the detailed explanation. As you mentioned, the solution here would be to perform the raycast only after the physics engine is updated. 

You should be able to achieve this by experimenting with the simulation delta time value set in the Perception Camera. Try setting it to the same number as your physics Fixed Timestamp (usually 0.02). This may fix the issue without the need to offset frames.

If that doesn't fix it, I recommend using two frames per each Iteration of your Scenario. Have `RotationRandomizer` perform the rotation in `OnIterationStart()` (which is the first frame of the Iteration). In `ExplorerEvent`, override the `Update` function to always trigger the raycasts one frame after the iteration starts instead of at the start of the iteration. You can do this by checking `Time.frameCount`.

**Comment by JonathanHUnity** [comment] 2021-03-26 20:30
Closing for now. Feel free to re-open if you continue to have trouble!

**Closed by JonathanHUnity** 2021-03-26 20:30 UTC
