### ISSUE TITLE
save instance segmentation to different folder for each object

### ISSUE THREAD

**Issue by an99990** [Unity-Technologies/com.unity.perception#458] opened 2022-03-29 17:50 UTC
Hi,
So i saw and issue reporting this enhancement https://github.com/Unity-Technologies/com.unity.perception/issues/404 but havent seen any update since. I believe theres some code that started [here](https://forum.unity.com/threads/instance-segmentation-for-separate-objects.1122772/), but it doesnt save the image. 

I am new to Unity world, can someone help me save the images in different folders ?
Thank you for any help

**Comment by csun** [comment] 2022-03-30 00:53
Hey there - the code in the forum post you linked should get you started on generating the actual images. The key is setting up the scenario so that it only shows one object per frame of capture. Then, you should start seeing that all of your instance segmentation images only contain a single object.

We don't directly support saving the images into different per-object folders, so your best course of action would probably be to write a separate script to post-process the data into your desired format. You could use our [dataset insights package](https://github.com/Unity-Technologies/datasetinsights) to write a python script that queries all captures for a certain object instance. Then you can use that capture's filename to move it into the proper folder.

**Comment by aryan-mann** [comment] 2022-04-07 19:33
Closing this issue for now as it's a duplicate of #404. We'll provide more updates on the thread for #404!
Let us know if you have any additional questions and thanks for using the Perception package 🎉

**Closed by aryan-mann** 2022-04-07 19:33 UTC
Labels: duplicate, enhancement
