### ISSUE TITLE
rgb and segmentation not the same

### ISSUE THREAD

**Issue by an99990** [Unity-Technologies/com.unity.perception#456] opened 2022-03-29 16:52 UTC
Hi,
I am not sure if its a bug or its me but i notice that the RGB image and RGB arent sync ?
I have put rgb_2 and instance_2 below as reference. 

![Instance_2](https://user-images.githubusercontent.com/87030365/160664636-ccb758c7-0896-47b7-8dfc-767cc84a3e63.png)
![rgb_2](https://user-images.githubusercontent.com/87030365/160664647-6c7f315e-3fa2-4178-9b34-1d0805fc6e93.png)

**Comment by sleal-unity** [comment] 2022-03-29 17:19
Hi @an99990,

What version of the perception package are you using in your project? Also, what option for anti-aliasing do you have selected in your main camera's inspector?

It seems that your RGB image is being flipped upside down, and it might be related to a rendering quirk I'm familiar with.

**Comment by an99990** [comment] 2022-03-29 17:24
Thanks for prompt answer : here are my answers
Unity 2020.3.32.f1
Unity perception 0.10.0-preview.1
![image](https://user-images.githubusercontent.com/87030365/160669854-1c6123ba-4313-4921-9c56-b624fac43c6a.png)

**Comment by an99990** [comment] 2022-03-29 17:37
Linux

**Comment by an99990** [comment] 2022-03-29 17:45
seems like a known issue ? : https://github.com/Unity-Technologies/com.unity.perception/issues/310

**Comment by sleal-unity** [comment] 2022-03-29 18:42
Yep, this issue is definitely something we've heard about and are tracking. Thanks for the confirmations!

**Comment by an99990** [comment] 2022-03-29 18:58
any workaround ? short term solution

**Comment by JonathanHUnity** [comment] 2022-03-30 18:29
We are working on a fix. @an99990 this issue should go away if you switch your project to use Vulkan instead of OpenGL. Can you confirm that this works for you?

**Comment by aryan-mann** [comment] 2022-04-07 15:52
Closing this for now as it's a duplicate of #310. Let us know if switching to Vulkan solved the issue!

**Closed by aryan-mann** 2022-04-07 15:52 UTC
Labels: duplicate
