### ISSUE TITLE
failed to create internal blit vertex shader

### ISSUE THREAD

**Issue by Neurotaur** [Unity-Technologies/com.unity.perception#223] opened 2021-02-24 17:32 UTC
Hi everyone,
I updated the Perception package from 0.6.0-preview.1 to 0.7.0-preview.2 I get the following error in the Console when I run the scene:

**d3d11: failed to create internal blit vertex shader, HR=80070057**

project HDRP
Unity Editor 2020.1.15f1

**Comment by mkamalza** [comment] 2021-02-24 18:49
Hi,

We suggest you update the HDRP package in your project and then use the "Reimport All" feature. To do this:
* Open Package Manager, find High Definition RP and check whether there is an update button available at the bottom right side of the window.
* Close Package Manager, right click on the Assets folder in the Project tab and click "Reimport All". 

Please let us know if these steps fix the issue.

**Comment by Neurotaur** [comment] 2021-02-24 22:38
The High Definition RP last version is already installed. I reimported all in Assets folder. 

- I get the same error.
- The dataset json files are ok. 
- The captured png files have no image.

Packages in project:
![antcity-package](https://user-images.githubusercontent.com/6352684/109074109-ebfba980-76bc-11eb-8c18-2e1b6fa815d3.png)

Console Error:
![d311-error](https://user-images.githubusercontent.com/6352684/109074593-94117280-76bd-11eb-9401-407755b77c10.png)

**Comment by mkamalza** [comment] 2021-02-24 22:49
Thank you for reporting back and the screenshots. Can you try another thing for us. Can you please create a new fresh HDRP project, install the latest version of the Perception package, and see if the problem persists?

I am trying to understand if this is an issue that was caused by the upgrade process, or if it exists in new projects too.

**Comment by Neurotaur** [comment] 2021-02-24 23:00
I tried with the same project with another camera game object with different properties values. The error disappear. 
Could be the Anti-aliasing property value?

![error-no-error](https://user-images.githubusercontent.com/6352684/109077423-b9a07b00-76c1-11eb-9c22-a087221ea10f.png)

**Comment by mkamalza** [comment] 2021-02-24 23:51
Good to know that disabling anti-aliasing is a possible workaround. That's not ideal though, since you should be able to use  anti-aliasing.

I can personally not reproduce this issue. So let's try one more thing on your side (besides the fresh project suggestion). Can you try and see if disabling the Perception Camera component makes a difference? 

If this error still happens while no Perception cameras are active, it is most likely not related to the Perception package, and could be a bug with HDRP. In this case, we would encourage you to report the bug using Unity's built-in bug reporter, or on Unity's forums, so that our teams can further investigate it.

**Comment by Neurotaur** [comment] 2021-02-25 15:44
I didn't get de error when I deactivate the Preception Camera script (see images).

![ptrvrpyion-activated](https://user-images.githubusercontent.com/6352684/109177946-f4e88b80-774d-11eb-8640-490f9d6a5c40.png)

![perception-deactivated](https://user-images.githubusercontent.com/6352684/109177911-ec905080-774d-11eb-8446-002a30a9f31b.png)

**Comment by Neurotaur** [comment] 2021-02-25 15:56
I am not an expert, but perhaps it could help in the analysis: I see in the Unity Editor title say <DX11> and if I run the dxdiag utility in my computer I can see "DirectX 12". The error prefix say "d3d11".

**Comment by mkamalza** [comment] 2021-02-25 21:13
Thank you for doing the test. The fact that your computer has DX12 on it is not related to the error. Unity Editor is simply using DX11 and that's why the error has "d3d11" in it. 

In order for us to be able to investigate this, we would need to have access to this Unity project. Would you be able to send a zip file of your project to us? We will need only three of the folders:
* Assets
* Packages
* ProjectSettings

**Comment by JonathanHUnity** [comment] 2021-03-26 20:28
As of [Release-0.8.0-preview.2](https://github.com/Unity-Technologies/com.unity.perception/releases/tag/Release-0.8.0-preview.2), you can now control the labeling by enabling or disabling the Lableing component. Thanks for the request!

**Comment by JonathanHUnity** [comment] 2021-04-29 17:53
Closing this for now. Feel free to reopen if this continues to be an issue

**Closed by JonathanHUnity** 2021-04-29 17:53 UTC
