### ISSUE TITLE
Support for post-processing

### ISSUE THREAD

**Issue by markuzo** [Unity-Technologies/com.unity.perception#303] opened 2021-04-26 13:06 UTC
Hi!

The documentation in PerceptionCamera.md states that post-processing is not supported. Are there plans to support this or should any post-processing take place after the image generation with Unity entirely?

I see that the post-processing effects do affect the visualization in both the Editor and Standalone Player, however, the captured RGB images do not have any of those effects.

**Comment by JonathanHUnity** [comment] 2021-04-28 15:15
Thank you for the report, we have confirmed this is a regression in the latest perception package. We hope to address this problem quickly.

**Comment by JonathanHUnity** [comment] 2021-04-29 18:19
An update to the com.unity.simulation.capture package has been released which addresses this issue. In the package manager in your project, upgrade "Unity Simulation Capture" to `com.unity.simulation.capture@0.0.10-preview.22`

**Comment by markuzo** [comment] 2021-04-30 08:03
I can confirm that the RGB captures now have the post-processing information in them, however, they are all flipped in Y. This inverting doesn't affect the InstanceSegmentation capture and only affects `preview.22` (I tried `preview.21` and the RGB captures were the right way up, but the post-processing stuff was gone). The images displayed in the Editor while in Play mode do not have a flip in the Y.

**Comment by mannewalis** [comment] 2021-04-30 14:50
Which platform, and graphics pipeline are you using?

**Comment by markuzo** [comment] 2021-04-30 15:26
I saw this issue on Windows, Unity 2020.3.3f1, URP, DX11. I normally build to Linux64 and MacUniversal, but I didn't test if it happens on these platforms as well.

**Comment by mannewalis** [comment] 2021-04-30 18:31
Hi again, which version of the perception package are you currently using?

**Comment by markuzo** [comment] 2021-04-30 18:55
`"com.unity.perception": "0.8.0-preview.3"`. When trying the new version of `com.unity.simulation.capture` I didn't change anything with the perception package.

**Comment by mannewalis** [comment] 2021-05-04 14:40
Hi again, so I am having some trouble reproducing this. I am using TestProjects/PerceptionURP on Windows with Unity 2020.3.3f1, and building a standalone app. The images so far are correct. I am wondering if there are some other differences between our projects that account for this. Can you give me a little more info on how you're setting up the perception package, and which settings are enabled/disabled, or even better, perhaps you could share part of your project, and I can try to diagnose the issue.

**Comment by markuzo** [comment] 2021-05-05 06:47
Exactly the same issue with reproducing the problem. 

In the same environment in a new Unity project, I couldn't reproduce the issue. Then I created a new scene in the same Unity project that is showing the issue, and got to the point where everything is identical to the problematic scene, but no issue. So in the same project, I have 2 seemingly identical scenes, one exhibiting the problem, and the other not. 

Closing the issue. I hope to reproduce it at some point, and will make a new issue accordingly.

**Comment by ChumbaWambalala** [comment] 2021-06-14 06:33
I'm experiencing the issue as well. Output images doesn't contain any post processing.
Unity 2020.3.3f1 and Perception Package 0.8.0-preview.3 - March 24, 2021

Here is what I'm expecting. Don't mind the characters :D
![image](https://user-images.githubusercontent.com/10083906/121847615-6ce9ba00-cd1b-11eb-9bf1-327243fee4de.png)

Here is a sample output. 
![image](https://user-images.githubusercontent.com/10083906/121847668-8428a780-cd1b-11eb-8840-f4c7d4d8d40a.png)


URP Settings
![URPSetting](https://user-images.githubusercontent.com/10083906/121848912-475db000-cd1d-11eb-8295-6284b2dd603f.jpg)

Forward Renderer Settings
![ForwardRenderingSettings](https://user-images.githubusercontent.com/10083906/121848931-4e84be00-cd1d-11eb-9816-b290674aae56.PNG)


Camera Settings
![CameraSetting](https://user-images.githubusercontent.com/10083906/121848942-52b0db80-cd1d-11eb-84dc-873dcf176ef3.png)

I tired the workarounds from this thread and nothing seems to be working.

**Comment by sleal-unity** [comment] 2021-06-15 19:08
Hi @ChumbaWambalala!

I can confirm that I've reproduced your issue and that the we've got a patch release (0.8.0-preview.4) coming soon for the perception package that will include a fix for this particular issue.

**Comment by sleal-unity** [comment] 2021-06-15 19:18
Here's a synopsis of the problems I've confirmed:
- The current perception release (version 0.8.0-preview.3) has a dependency on the com.unity.simulation.capture package (version 0.0.10-preview.20)
- This version of the capture package, preview.20, as well as preview.21 have an issue of not capturing post processing effects
- The capture package version of preview.22 fixes this issue, but flips all rendered images upside down when the camera's anti-aliasing setting is set to None while post processing effects are enabled
- Finally, we have a new capture package version preview.23 that fixes all the issues being released very soon
- The perception package will also receive a patch update soon to upgrade its capture package dependency to preview.23 once it is available

**Comment by ChumbaWambalala** [comment] 2021-06-16 02:05
Hi Steven,

That's great news to hear! Thank you so much.
I've been into synth for the past years, I've been juggling through Unity
Perception Tools and Nvidia Dataset Synthesizer in Unreal.
So far, I really like how Unity's approach on this, it's much more feature
packed and easier to use.

Just sharing my appreciation of the tool.
I'm excited for your next release.

Best,
Ed

**Comment by JonathanHUnity** [comment] 2021-11-08 16:58
The 0.9.0 version was just released which should fix all of these issues. Let us know if you run into more trouble!

**Closed by JonathanHUnity** 2021-11-08 16:58 UTC
Labels: bug
